// Code generated by enumify v1.1.1. DO NOT EDIT.
package prompts

import (
	"go.rtnl.ai/enumify"
	"testing"
)

func TestRole(t *testing.T) {
	suite := enumify.TestSuite[Role, []string]{
		Values: []Role{RoleUnknown, RoleUser, RoleSystem, RoleDeveloper, RoleAssistant, RoleTool, RoleFunction},
		Names:  roleNames,
		ICase:  true,
		ISpace: true,
	}

	suite.Run(t)
}
