// Code generated by enumify v1.1.1. DO NOT EDIT.
package prompts

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"go.rtnl.ai/enumify"
)

//============================================================================
// Role Enum Type: Generated Functions and Methods
//============================================================================

var roleParser func(any) (Role, error) = enumify.ParseFactory[Role](roleNames)

// ParseRole parses the given value into a Role.
func ParseRole(r any) (Role, error) {
	return roleParser(r)
}

// Ensure Role implements fmt.Stringer.
func (r Role) String() string {
	if r >= Role(len(roleNames)) {
		return roleNames[RoleUnknown]
	}
	return roleNames[r]
}

// Ensure Role implements text.Marshaler.
func (r Role) MarshalText() ([]byte, error) {
	return []byte(r.String()), nil
}

// Ensure Role implements text.Unmarshaler.
func (r *Role) UnmarshalText(data []byte) (err error) {
	*r, err = ParseRole(string(data))
	return err
}

// Ensure Role implements binary.Marshaler.
func (r Role) MarshalBinary() ([]byte, error) {
	return []byte{byte(r)}, nil
}

// Ensure Role implements binary.Unmarshaler.
func (r *Role) UnmarshalBinary(data []byte) (err error) {
	switch len(data) {
	case 0:
		*r = Role(0)
		return nil
	case 1:
		*r = Role(data[0])
		return nil
	default:
		return fmt.Errorf("cannot unmarshal %d bytes into Role", len(data))
	}
}

// Ensure Role implements json.Marshaler.
func (r Role) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.String())
}

// Ensure Role implements json.Unmarshaler.
func (r *Role) UnmarshalJSON(data []byte) (err error) {
	var sv any
	if err = json.Unmarshal(data, &sv); err != nil {
		return err
	}

	if *r, err = ParseRole(sv); err != nil {
		return err
	}
	return nil
}

// Ensure Role implements yaml.Marshaler.
func (r Role) MarshalYAML() (any, error) {
	return r.String(), nil
}

// Ensure Role implements yaml.Unmarshaler.
func (r *Role) UnmarshalYAML(unmarshal func(any) error) (err error) {
	var sv string
	if err = unmarshal(&sv); err != nil {
		return err
	}

	if *r, err = ParseRole(sv); err != nil {
		return err
	}
	return nil
}

// Ensure Role implements sql.Scanner.
func (r *Role) Scan(src any) (err error) {
	switch val := src.(type) {
	case nil:
		return nil
	case string:
		*r, err = ParseRole(val)
		return err
	case []byte:
		*r, err = ParseRole(string(val))
		return err
	default:
		return fmt.Errorf("cannot scan %T into Role", val)
	}
}

// Ensure Role implements driver.Valuer.
func (r Role) Value() (driver.Value, error) {
	return r.String(), nil
}
