// Code generated by enumify v1.1.1. DO NOT EDIT.
package auth

import (
	"go.rtnl.ai/enumify"
	"testing"
)

func TestType(t *testing.T) {
	suite := enumify.TestSuite[Type, []string]{
		Values: []Type{TypeUnknown, TypeAPIKey, TypeToken, TypeBasic, TypeOAuth2Client, TypeOAuth2Token, TypeOpenAIOrganization, TypeNone},
		Names:  typeNames,
		ICase:  true,
		ISpace: true,
	}

	suite.Run(t)
}
