// Code generated by enumify v1.1.1. DO NOT EDIT.
package types

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"go.rtnl.ai/enumify"
)

//============================================================================
// APIType Enum Type: Generated Functions and Methods
//============================================================================

var aPITypeParser func(any) (APIType, error) = enumify.ParseFactory[APIType](apiTypeNames)

// ParseAPIType parses the given value into a APIType.
func ParseAPIType(a any) (APIType, error) {
	return aPITypeParser(a)
}

// Ensure APIType implements fmt.Stringer.
func (a APIType) String() string {
	if a >= APIType(len(apiTypeNames[0])) {
		return apiTypeNames[0][APITypeUnknown]
	}
	return apiTypeNames[0][a]
}

// Ensure APIType implements text.Marshaler.
func (a APIType) MarshalText() ([]byte, error) {
	return []byte(a.String()), nil
}

// Ensure APIType implements text.Unmarshaler.
func (a *APIType) UnmarshalText(data []byte) (err error) {
	*a, err = ParseAPIType(string(data))
	return err
}

// Ensure APIType implements binary.Marshaler.
func (a APIType) MarshalBinary() ([]byte, error) {
	return []byte{byte(a)}, nil
}

// Ensure APIType implements binary.Unmarshaler.
func (a *APIType) UnmarshalBinary(data []byte) (err error) {
	switch len(data) {
	case 0:
		*a = APIType(0)
		return nil
	case 1:
		*a = APIType(data[0])
		return nil
	default:
		return fmt.Errorf("cannot unmarshal %d bytes into APIType", len(data))
	}
}

// Ensure APIType implements json.Marshaler.
func (a APIType) MarshalJSON() ([]byte, error) {
	return json.Marshal(a.String())
}

// Ensure APIType implements json.Unmarshaler.
func (a *APIType) UnmarshalJSON(data []byte) (err error) {
	var sv any
	if err = json.Unmarshal(data, &sv); err != nil {
		return err
	}

	if *a, err = ParseAPIType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure APIType implements yaml.Marshaler.
func (a APIType) MarshalYAML() (any, error) {
	return a.String(), nil
}

// Ensure APIType implements yaml.Unmarshaler.
func (a *APIType) UnmarshalYAML(unmarshal func(any) error) (err error) {
	var sv string
	if err = unmarshal(&sv); err != nil {
		return err
	}

	if *a, err = ParseAPIType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure APIType implements sql.Scanner.
func (a *APIType) Scan(src any) (err error) {
	switch val := src.(type) {
	case nil:
		return nil
	case string:
		*a, err = ParseAPIType(val)
		return err
	case []byte:
		*a, err = ParseAPIType(string(val))
		return err
	default:
		return fmt.Errorf("cannot scan %T into APIType", val)
	}
}

// Ensure APIType implements driver.Valuer.
func (a APIType) Value() (driver.Value, error) {
	return a.String(), nil
}
