// Code generated by enumify v1.1.1. DO NOT EDIT.
package types

import (
	"go.rtnl.ai/enumify"
	"testing"
)

func TestProviderType(t *testing.T) {
	suite := enumify.TestSuite[ProviderType, [][]string]{
		Values: []ProviderType{ProviderTypeUnknown, ProviderTypeMock, ProviderTypeOpenAI, ProviderTypeOpenAICompatible, ProviderTypeOpenRouter},
		Names:  providerTypeNames,
		ICase:  true,
		ISpace: true,
	}

	suite.Run(t)
}
