// Code generated by enumify v1.1.1. DO NOT EDIT.
package types

import (
	"go.rtnl.ai/enumify"
	"testing"
)

func TestStatus(t *testing.T) {
	suite := enumify.TestSuite[Status, [][]string]{
		Values: []Status{StatusUnknown, StatusPending, StatusDisabled, StatusDisconnected, StatusInitializing, StatusConnected, StatusError, StatusAuthRequired, StatusRegRequired},
		Names:  statusNames,
		ICase:  true,
		ISpace: true,
	}

	suite.Run(t)
}
