// Code generated by enumify v1.1.1. DO NOT EDIT.
package api

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"go.rtnl.ai/enumify"
)

//============================================================================
// OutputType Enum Type: Generated Functions and Methods
//============================================================================

var outputTypeParser func(any) (OutputType, error) = enumify.ParseFactory[OutputType](outputTypeNames)

// ParseOutputType parses the given value into a OutputType.
func ParseOutputType(o any) (OutputType, error) {
	return outputTypeParser(o)
}

// Ensure OutputType implements fmt.Stringer.
func (o OutputType) String() string {
	if o >= OutputType(len(outputTypeNames)) {
		return outputTypeNames[OutputUnknown]
	}
	return outputTypeNames[o]
}

// Ensure OutputType implements text.Marshaler.
func (o OutputType) MarshalText() ([]byte, error) {
	return []byte(o.String()), nil
}

// Ensure OutputType implements text.Unmarshaler.
func (o *OutputType) UnmarshalText(data []byte) (err error) {
	*o, err = ParseOutputType(string(data))
	return err
}

// Ensure OutputType implements binary.Marshaler.
func (o OutputType) MarshalBinary() ([]byte, error) {
	return []byte{byte(o)}, nil
}

// Ensure OutputType implements binary.Unmarshaler.
func (o *OutputType) UnmarshalBinary(data []byte) (err error) {
	switch len(data) {
	case 0:
		*o = OutputType(0)
		return nil
	case 1:
		*o = OutputType(data[0])
		return nil
	default:
		return fmt.Errorf("cannot unmarshal %d bytes into OutputType", len(data))
	}
}

// Ensure OutputType implements json.Marshaler.
func (o OutputType) MarshalJSON() ([]byte, error) {
	return json.Marshal(o.String())
}

// Ensure OutputType implements json.Unmarshaler.
func (o *OutputType) UnmarshalJSON(data []byte) (err error) {
	var sv any
	if err = json.Unmarshal(data, &sv); err != nil {
		return err
	}

	if *o, err = ParseOutputType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure OutputType implements yaml.Marshaler.
func (o OutputType) MarshalYAML() (any, error) {
	return o.String(), nil
}

// Ensure OutputType implements yaml.Unmarshaler.
func (o *OutputType) UnmarshalYAML(unmarshal func(any) error) (err error) {
	var sv string
	if err = unmarshal(&sv); err != nil {
		return err
	}

	if *o, err = ParseOutputType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure OutputType implements sql.Scanner.
func (o *OutputType) Scan(src any) (err error) {
	switch val := src.(type) {
	case nil:
		return nil
	case string:
		*o, err = ParseOutputType(val)
		return err
	case []byte:
		*o, err = ParseOutputType(string(val))
		return err
	default:
		return fmt.Errorf("cannot scan %T into OutputType", val)
	}
}

// Ensure OutputType implements driver.Valuer.
func (o OutputType) Value() (driver.Value, error) {
	return o.String(), nil
}
