// Code generated by enumify v1.1.1. DO NOT EDIT.
package render

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"go.rtnl.ai/enumify"
)

//============================================================================
// Type Enum Type: Generated Functions and Methods
//============================================================================

var typeParser func(any) (Type, error) = enumify.ParseFactory[Type](typeNames)

// ParseType parses the given value into a Type.
func ParseType(t any) (Type, error) {
	return typeParser(t)
}

// Ensure Type implements fmt.Stringer.
func (t Type) String() string {
	if t >= Type(len(typeNames)) {
		return typeNames[Unknown]
	}
	return typeNames[t]
}

// Ensure Type implements text.Marshaler.
func (t Type) MarshalText() ([]byte, error) {
	return []byte(t.String()), nil
}

// Ensure Type implements text.Unmarshaler.
func (t *Type) UnmarshalText(data []byte) (err error) {
	*t, err = ParseType(string(data))
	return err
}

// Ensure Type implements binary.Marshaler.
func (t Type) MarshalBinary() ([]byte, error) {
	return []byte{byte(t)}, nil
}

// Ensure Type implements binary.Unmarshaler.
func (t *Type) UnmarshalBinary(data []byte) (err error) {
	switch len(data) {
	case 0:
		*t = Type(0)
		return nil
	case 1:
		*t = Type(data[0])
		return nil
	default:
		return fmt.Errorf("cannot unmarshal %d bytes into Type", len(data))
	}
}

// Ensure Type implements json.Marshaler.
func (t Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.String())
}

// Ensure Type implements json.Unmarshaler.
func (t *Type) UnmarshalJSON(data []byte) (err error) {
	var sv any
	if err = json.Unmarshal(data, &sv); err != nil {
		return err
	}

	if *t, err = ParseType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure Type implements yaml.Marshaler.
func (t Type) MarshalYAML() (any, error) {
	return t.String(), nil
}

// Ensure Type implements yaml.Unmarshaler.
func (t *Type) UnmarshalYAML(unmarshal func(any) error) (err error) {
	var sv string
	if err = unmarshal(&sv); err != nil {
		return err
	}

	if *t, err = ParseType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure Type implements sql.Scanner.
func (t *Type) Scan(src any) (err error) {
	switch val := src.(type) {
	case nil:
		return nil
	case string:
		*t, err = ParseType(val)
		return err
	case []byte:
		*t, err = ParseType(string(val))
		return err
	default:
		return fmt.Errorf("cannot scan %T into Type", val)
	}
}

// Ensure Type implements driver.Valuer.
func (t Type) Value() (driver.Value, error) {
	return t.String(), nil
}
