// Code generated by enumify v1.1.1. DO NOT EDIT.
package render

import (
	"go.rtnl.ai/enumify"
	"testing"
)

func TestType(t *testing.T) {
	suite := enumify.TestSuite[Type, []string]{
		Values: []Type{Unknown, Sprintf, Jinja, Go},
		Names:  typeNames,
		ICase:  true,
		ISpace: true,
	}

	suite.Run(t)
}
