// Code generated by enumify v1.1.1. DO NOT EDIT.
package provider

import (
	"go.rtnl.ai/enumify"
	"testing"
)

func TestAPIType(t *testing.T) {
	suite := enumify.TestSuite[APIType, [][]string]{
		Values: []APIType{APITypeUnknown, APITypeMock, APITypeOpenAIResponses, APITypeOpenAIChatCompletions},
		Names:  apiTypeNames,
		ICase:  true,
		ISpace: true,
	}

	suite.Run(t)
}
