// Code generated by enumify v1.1.1. DO NOT EDIT.
package provider

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"go.rtnl.ai/enumify"
)

//============================================================================
// ProviderType Enum Type: Generated Functions and Methods
//============================================================================

var providerTypeParser func(any) (ProviderType, error) = enumify.ParseFactory[ProviderType](providerTypeNames)

// ParseProviderType parses the given value into a ProviderType.
func ParseProviderType(p any) (ProviderType, error) {
	return providerTypeParser(p)
}

// Ensure ProviderType implements fmt.Stringer.
func (p ProviderType) String() string {
	if p >= ProviderType(len(providerTypeNames[0])) {
		return providerTypeNames[0][ProviderTypeUnknown]
	}
	return providerTypeNames[0][p]
}

// Ensure ProviderType implements text.Marshaler.
func (p ProviderType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

// Ensure ProviderType implements text.Unmarshaler.
func (p *ProviderType) UnmarshalText(data []byte) (err error) {
	*p, err = ParseProviderType(string(data))
	return err
}

// Ensure ProviderType implements binary.Marshaler.
func (p ProviderType) MarshalBinary() ([]byte, error) {
	return []byte{byte(p)}, nil
}

// Ensure ProviderType implements binary.Unmarshaler.
func (p *ProviderType) UnmarshalBinary(data []byte) (err error) {
	switch len(data) {
	case 0:
		*p = ProviderType(0)
		return nil
	case 1:
		*p = ProviderType(data[0])
		return nil
	default:
		return fmt.Errorf("cannot unmarshal %d bytes into ProviderType", len(data))
	}
}

// Ensure ProviderType implements json.Marshaler.
func (p ProviderType) MarshalJSON() ([]byte, error) {
	return json.Marshal(p.String())
}

// Ensure ProviderType implements json.Unmarshaler.
func (p *ProviderType) UnmarshalJSON(data []byte) (err error) {
	var sv any
	if err = json.Unmarshal(data, &sv); err != nil {
		return err
	}

	if *p, err = ParseProviderType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure ProviderType implements yaml.Marshaler.
func (p ProviderType) MarshalYAML() (any, error) {
	return p.String(), nil
}

// Ensure ProviderType implements yaml.Unmarshaler.
func (p *ProviderType) UnmarshalYAML(unmarshal func(any) error) (err error) {
	var sv string
	if err = unmarshal(&sv); err != nil {
		return err
	}

	if *p, err = ParseProviderType(sv); err != nil {
		return err
	}
	return nil
}

// Ensure ProviderType implements sql.Scanner.
func (p *ProviderType) Scan(src any) (err error) {
	switch val := src.(type) {
	case nil:
		return nil
	case string:
		*p, err = ParseProviderType(val)
		return err
	case []byte:
		*p, err = ParseProviderType(string(val))
		return err
	default:
		return fmt.Errorf("cannot scan %T into ProviderType", val)
	}
}

// Ensure ProviderType implements driver.Valuer.
func (p ProviderType) Value() (driver.Value, error) {
	return p.String(), nil
}
