// Code generated by enumify v1.1.1. DO NOT EDIT.
package provider

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"go.rtnl.ai/enumify"
)

//============================================================================
// Status Enum Type: Generated Functions and Methods
//============================================================================

var statusParser func(any) (Status, error) = enumify.ParseFactory[Status](statusNames)

// ParseStatus parses the given value into a Status.
func ParseStatus(s any) (Status, error) {
	return statusParser(s)
}

// Ensure Status implements fmt.Stringer.
func (s Status) String() string {
	if s >= Status(len(statusNames[0])) {
		return statusNames[0][StatusUnknown]
	}
	return statusNames[0][s]
}

// Ensure Status implements text.Marshaler.
func (s Status) MarshalText() ([]byte, error) {
	return []byte(s.String()), nil
}

// Ensure Status implements text.Unmarshaler.
func (s *Status) UnmarshalText(data []byte) (err error) {
	*s, err = ParseStatus(string(data))
	return err
}

// Ensure Status implements binary.Marshaler.
func (s Status) MarshalBinary() ([]byte, error) {
	return []byte{byte(s)}, nil
}

// Ensure Status implements binary.Unmarshaler.
func (s *Status) UnmarshalBinary(data []byte) (err error) {
	switch len(data) {
	case 0:
		*s = Status(0)
		return nil
	case 1:
		*s = Status(data[0])
		return nil
	default:
		return fmt.Errorf("cannot unmarshal %d bytes into Status", len(data))
	}
}

// Ensure Status implements json.Marshaler.
func (s Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

// Ensure Status implements json.Unmarshaler.
func (s *Status) UnmarshalJSON(data []byte) (err error) {
	var sv any
	if err = json.Unmarshal(data, &sv); err != nil {
		return err
	}

	if *s, err = ParseStatus(sv); err != nil {
		return err
	}
	return nil
}

// Ensure Status implements yaml.Marshaler.
func (s Status) MarshalYAML() (any, error) {
	return s.String(), nil
}

// Ensure Status implements yaml.Unmarshaler.
func (s *Status) UnmarshalYAML(unmarshal func(any) error) (err error) {
	var sv string
	if err = unmarshal(&sv); err != nil {
		return err
	}

	if *s, err = ParseStatus(sv); err != nil {
		return err
	}
	return nil
}

// Ensure Status implements sql.Scanner.
func (s *Status) Scan(src any) (err error) {
	switch val := src.(type) {
	case nil:
		return nil
	case string:
		*s, err = ParseStatus(val)
		return err
	case []byte:
		*s, err = ParseStatus(string(val))
		return err
	default:
		return fmt.Errorf("cannot scan %T into Status", val)
	}
}

// Ensure Status implements driver.Valuer.
func (s Status) Value() (driver.Value, error) {
	return s.String(), nil
}
